export enum PermissionName {
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  CLIENT_VIEW = 'CLIENT_VIEW',
  CLIENT_CREATE = 'CLIENT_CREATE',
  CLIENT_UPDATE = 'CLIENT_UPDATE',
  CLIENT_DELETE = 'CLIENT_DELETE',

  SERVICE_VIEW = 'SERVICE_VIEW',
  SERVICE_CREATE = 'SERVICE_CREATE',
  SERVICE_UPDATE = 'SERVICE_UPDATE',
  SERVICE_DELETE = 'SERVICE_DELETE',

  APPLICATION_VIEW = 'APPLICATION_VIEW',
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  APPLICATION_UPDATE = 'APPLICATION_UPDATE',
  APPLICATION_DELETE = 'APPLICATION_DELETE',

  DOCUMENT_VIEW = 'DOCUMENT_VIEW',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_VERIFY = 'DOCUMENT_VERIFY',
  DOCUMENT_REJECT = 'DOCUMENT_REJECT',
  DOCUMENT_DELETE = 'DOCUMENT_DELETE',

  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_MANAGE = 'PAYMENT_MANAGE',

  APPOINTMENT_VIEW = 'APPOINTMENT_VIEW',
  APPOINTMENT_MANAGE = 'APPOINTMENT_MANAGE',

  MESSAGE_VIEW = 'MESSAGE_VIEW',
  MESSAGE_SEND = 'MESSAGE_SEND',

  BLOG_VIEW = 'BLOG_VIEW',
  BLOG_MANAGE = 'BLOG_MANAGE',

  FAQ_VIEW = 'FAQ_VIEW',
  FAQ_MANAGE = 'FAQ_MANAGE',

  REPORT_VIEW = 'REPORT_VIEW',
  AUDIT_VIEW = 'AUDIT_VIEW',
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
}
